version: '3'
services:
  redis_user:
    container_name: redis
    image: redis:latest

  mongodb:
    container_name: mongodb  
    image: mongo:latest

  frontend-service:
    container_name: frontend-service
    build: ./frontend
    ports:
      - 3000:3000

  gateway-service:
    env_file: # To be deleted
      - ./gateway-service/.env.prod
    container_name: gateway-service
    build: ./gateway-service
    ports:
      - 80:80
    depends_on:
      - user-service
      - matching-service
      - question-service
      - user-history-service

  auth-service:
    env_file: # To be deleted
      - ./auth-service/.env.prod
    container_name: auth-service
    build: ./auth-service
    depends_on:
      - redis_user

  user-service:
    env_file: # To be deleted
      - ./user-service/.env.prod
    container_name: user-service
    build: ./user-service
    depends_on:
      - redis_user
      - mongodb

  matching-service:
    env_file: # To be deleted
      - ./matching-service/.env.prod
    container_name: matching-service
    build: ./matching-service
    ports:
      - 8001:8001
    depends_on:
      - mongodb

  question-service:
    env_file: # To be deleted
      - ./question-service/.env.prod
    container_name: question-service
    build: ./question-service
    depends_on:
      - mongodb

  user-history-service:
    env_file: # To be deleted
      - ./user-history-service/.env.prod
    container_name: user-history-service
    build: ./user-history-service
    depends_on:
      - mongodb
