version: '3'
services:
  redis_user:
    container_name: redis
    image: redis:latest



  mongodb:
    container_name: mongodb  
    image: mongo:latest


  frontend-service:
    container_name: frontend-service
    build: ./frontend
    ports:
      - 3000:3000

  user-service:
    env_file: # To be deleted
      - ./user-service/.env.prod
    container_name: user-service
    build: ./user-service
    ports:
      - 8000:8000
    depends_on:
      - redis_user
      - mongodb


  matching-service:
    env_file: # To be deleted
      - ./matching-service/.env.prod
    container_name: matching-service
    build: ./matching-service
    ports:
      - 8001:8001
    depends_on:
      - mongodb

  question-service:
    env_file: # To be deleted
      - ./question-service/.env.prod
    container_name: question-service
    build: ./question-service
    ports:
      - 8002:8002
    depends_on:
      - mongodb
