name: Build and Deploy User Service to AWS

on:
 pull_request:
    branches: 
      - main
    types: 
      - closed
    paths:
      - ./user-service/**

jobs:
  deploy_aws:
    runs-on: ubuntu-18.04
    steps:      

    - name: Obtain PR commit SHA
      id: pr_commit
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ap-southeast-1

    - name: Log in to Amazon ECR
      id: login-ecr 
      uses: aws-actions/amazon-ecr-Login@v1

    - name: Build, tag, and push image to Amazon ECR 
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.pr_commit.outputs.sha_short }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./user-service/Dockerfile
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Log out of Amazon ECR
      if: always() 
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
