name: Gateway Service CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'gateway-service/**'

jobs:
  test_gateway:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']
        redis-version: [4]

    steps:
      - uses: actions/checkout@v3
      
      # Create env.prod files per  for local testing

      - name: Orchestrate microservices
        run: docker-compose -f "docker-compose.yml" up -d --build
        working-directory: ./

      - name: Install dependencies to test Gateway Service
        run: npm ci
        working-directory: ./gateway-service/tests

      - name: Test Gateway Service
        run: npm test
        working-directory: ./gateway-service/tests
