name: User Service CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'user-service/**'

jobs:
  test_user:
    defaults:
      run:
        working-directory: ./user-service

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']
        redis-version: [4]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
            mongodb-version: ${{ matrix.mongodb-version }}
            mongodb-port: 27017
      

      - name: Install Node dependencies
        run: npm ci

      - name: Lint User Service Code
        run: npm run lint

      - name: Test User Service
        run: npm test 
        env:
            DB_LOCAL_URI: ${{ secrets.DB_LOCAL_URI }}
            ENV: ${{ secrets.ENV }}
            REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            VERIFICATION_TOKEN_SECRET: ${{ secrets.VERIFICATION_TOKEN_SECRET }}
            REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
            ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
            VERIFICATION_TOKEN_EXPIRY: ${{ secrets.VERIFICATION_TOKEN_EXPIRY }}
            EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
            EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
